openapi: 3.0.0
info:
  title: Example API
  version: 1.0.0
  description: QnA와 Tip 데이터를 가져오는 API
paths:
  /api/qna:
    get:
      summary: QnA 데이터 가져오기
      description: 데이터베이스에서 QnA 데이터를 가져옵니다.
      responses:
        "200":
          description: 성공적으로 데이터 반환
          content:
            application/json:
              schema:
                type: object
                properties:
                  answer_list:
                    type: array
                    items:
                      type: object
                      properties:
                        Ranswer:
                          type: string
                          description: QnA 답변의 ID
                        user_grade:
                          type: string
                          description: 사용자 등급
                        name:
                          type: string
                          description: 사용자의 이름
                        level:
                          type: integer
                          description: 사용자 레벨
                        hakbu:
                          type: string
                          description: 사용자의 학부
              example:
                answer_list:
                  - Ranswer: "123456"
                    user_grade: "A"
                    name: "John Doe"
                    level: 5
                    hakbu: "Computer Science"
        "500":
          description: 서버 내부 오류
  /api/tips:
    get:
      summary: Tip 데이터 가져오기
      description: 데이터베이스에서 Tip 데이터를 가져옵니다.
      responses:
        "200":
          description: 성공적으로 데이터 반환
          content:
            application/json:
              schema:
                type: object
                properties:
                  title:
                    type: string
                    description: 팁 제목
                  content:
                    type: string
                    description: 팁 내용
                  createdAt:
                    type: string
                    format: date-time
                    description: 생성 날짜
              example:
                title: "유용한 팁"
                content: "이것은 유용한 팁입니다."
                createdAt: "2024-08-31T23:12:19Z"
        "500":
          description: 서버 내부 오류
